// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Soporte GoFrioCalor",
            "email": "soporte@gofrocalor.com"
        },
        "license": {
            "name": "Propietario",
            "url": "https://gofrocalor.com/license"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deliveries": {
            "get": {
                "description": "Obtiene todas las entregas, opcionalmente filtradas por número de cuenta y/o fecha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Listar entregas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de cuenta",
                        "name": "nro_cta",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha de acción (formato: YYYY-MM-DD)",
                        "name": "fecha_accion",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GoFrioCalor_internal_dto.DeliveryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una nueva entrega en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Crear entrega",
                "parameters": [
                    {
                        "description": "Datos de la entrega",
                        "name": "delivery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.Delivery"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.DeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deliveries/by-rto": {
            "get": {
                "description": "Obtiene entregas filtradas por número de RTO y opcionalmente por fecha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Listar entregas por RTO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número de RTO",
                        "name": "nro_rto",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha de acción (formato: YYYY-MM-DD)",
                        "name": "fecha_accion",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GoFrioCalor_internal_dto.DeliveryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deliveries/infobip": {
            "post": {
                "description": "Crea una entrega desde el chatbot de Infobip con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Crear entrega desde Infobip",
                "parameters": [
                    {
                        "description": "Datos de la entrega desde Infobip",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.InfobipDeliveryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.InfobipDeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deliveries/{id}": {
            "get": {
                "description": "Obtiene los detalles de una entrega específica por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Obtener entrega por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la entrega",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.DeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza los datos de una entrega existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Actualizar entrega",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la entrega",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados de la entrega",
                        "name": "delivery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.Delivery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.Delivery"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina una entrega del sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deliveries"
                ],
                "summary": "Eliminar entrega",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la entrega",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mobile/complete-delivery": {
            "post": {
                "description": "Marca la entrega como completada y publica mensaje para crear orden de trabajo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile"
                ],
                "summary": "Completar entrega",
                "parameters": [
                    {
                        "description": "Información de la entrega completada",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.MobileCompleteDeliveryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.MobileCompleteDeliveryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mobile/validate-dispenser": {
            "post": {
                "description": "Valida que el dispenser escaneado pertenezca al delivery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile"
                ],
                "summary": "Validar dispenser escaneado",
                "parameters": [
                    {
                        "description": "Información del dispenser",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.ValidateDispenserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.ValidateDispenserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mobile/validate-token": {
            "post": {
                "description": "El repartidor valida el token proporcionado por el cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile"
                ],
                "summary": "Validar token de entrega",
                "parameters": [
                    {
                        "description": "Token del cliente",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.ValidateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.ValidateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/work-orders/generate": {
            "post": {
                "description": "Genera un PDF con la orden de trabajo basada en los datos de la entrega",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Work Orders"
                ],
                "summary": "Generar orden de trabajo",
                "parameters": [
                    {
                        "description": "Datos de la orden de trabajo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GoFrioCalor_internal_dto.WorkOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF generado exitosamente",
                        "schema": {
                            "type": "file"
                        },
                        "headers": {
                            "X-Order-Number": {
                                "type": "string",
                                "description": "Número de orden generado"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error al generar PDF",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GoFrioCalor_internal_dto.DeliveryInfoDTO": {
            "type": "object",
            "properties": {
                "cantidad": {
                    "type": "integer"
                },
                "fecha_accion": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nro_cta": {
                    "type": "string"
                },
                "nro_rto": {
                    "type": "string"
                },
                "tipo_entrega": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_dto.DeliveryResponse": {
            "type": "object",
            "properties": {
                "cantidad": {
                    "type": "integer"
                },
                "dispensers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GoFrioCalor_internal_dto.DispenserResponse"
                    }
                },
                "entregado_por": {
                    "$ref": "#/definitions/GoFrioCalor_internal_models.EntregadoPor"
                },
                "estado": {
                    "$ref": "#/definitions/GoFrioCalor_internal_models.EstadoEntrega"
                },
                "fecha_accion": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nro_cta": {
                    "type": "string"
                },
                "nro_rto": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "tipo_entrega": {
                    "$ref": "#/definitions/GoFrioCalor_internal_models.TipoEntrega"
                },
                "tipos_dispensers": {
                    "$ref": "#/definitions/GoFrioCalor_internal_dto.DispenserTypesCount"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_dto.DispenserCompletedDTO": {
            "type": "object",
            "properties": {
                "marca": {
                    "type": "string"
                },
                "nro_serie": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_dto.DispenserInfoDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string"
                },
                "nro_serie": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "GoFrioCalor_internal_dto.DispenserResponse": {
            "type": "object",
            "properties": {
                "marca": {
                    "type": "string"
                },
                "nro_serie": {
                    "type": "string"
                },
                "tipo": {
                    "$ref": "#/definitions/GoFrioCalor_internal_models.TipoDispenser"
                }
            }
        },
        "GoFrioCalor_internal_dto.DispenserTypesCount": {
            "type": "object",
            "properties": {
                "M": {
                    "type": "integer"
                },
                "P": {
                    "type": "integer"
                }
            }
        },
        "GoFrioCalor_internal_dto.DispenserTypesQuantity": {
            "type": "object",
            "properties": {
                "M": {
                    "description": "Dispensers de Mesada",
                    "type": "integer"
                },
                "P": {
                    "description": "Dispensers de Pie",
                    "type": "integer"
                }
            }
        },
        "GoFrioCalor_internal_dto.InfobipDeliveryRequest": {
            "type": "object",
            "required": [
                "entregado_por",
                "nro_cta",
                "nro_rto",
                "session_id",
                "tipo_entrega",
                "tipos"
            ],
            "properties": {
                "entregado_por": {
                    "enum": [
                        "Repartidor",
                        "Tecnico"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.EntregadoPor"
                        }
                    ]
                },
                "fecha_accion": {
                    "type": "string"
                },
                "nro_cta": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "nro_rto": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "session_id": {
                    "type": "string",
                    "minLength": 1
                },
                "tipo_entrega": {
                    "enum": [
                        "Instalacion",
                        "Retiro",
                        "Recambio"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.TipoEntrega"
                        }
                    ]
                },
                "tipos": {
                    "$ref": "#/definitions/GoFrioCalor_internal_dto.DispenserTypesQuantity"
                }
            }
        },
        "GoFrioCalor_internal_dto.InfobipDeliveryResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_dto.MobileCompleteDeliveryRequest": {
            "type": "object",
            "required": [
                "delivery_id",
                "token",
                "validated_dispensers"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "delivery_id": {
                    "type": "integer"
                },
                "locality": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "validated_dispensers": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "GoFrioCalor_internal_dto.MobileCompleteDeliveryResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dispensers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GoFrioCalor_internal_dto.DispenserCompletedDTO"
                    }
                },
                "locality": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nroCta": {
                    "type": "string"
                },
                "nroRto": {
                    "type": "string"
                },
                "tipoAccion": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "work_order_queued": {
                    "type": "boolean"
                }
            }
        },
        "GoFrioCalor_internal_dto.ValidateDispenserRequest": {
            "type": "object",
            "required": [
                "delivery_id",
                "nro_serie"
            ],
            "properties": {
                "delivery_id": {
                    "type": "integer"
                },
                "nro_serie": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_dto.ValidateDispenserResponse": {
            "type": "object",
            "properties": {
                "dispenser": {
                    "$ref": "#/definitions/GoFrioCalor_internal_dto.DispenserInfoDTO"
                },
                "message": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "GoFrioCalor_internal_dto.ValidateTokenRequest": {
            "type": "object",
            "required": [
                "fecha_accion",
                "nro_cta",
                "token"
            ],
            "properties": {
                "fecha_accion": {
                    "type": "string"
                },
                "nro_cta": {
                    "type": "string"
                },
                "token": {
                    "type": "string",
                    "minLength": 4
                }
            }
        },
        "GoFrioCalor_internal_dto.ValidateTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "GoFrioCalor_internal_dto.WorkOrderDispenserRequest": {
            "type": "object",
            "required": [
                "marca",
                "nro_serie"
            ],
            "properties": {
                "marca": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "nro_serie": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "GoFrioCalor_internal_dto.WorkOrderRequest": {
            "type": "object",
            "required": [
                "address",
                "createdAt",
                "locality",
                "name",
                "nroCta",
                "nroRto",
                "tipoAccion"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 5
                },
                "createdAt": {
                    "type": "string"
                },
                "dispensers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GoFrioCalor_internal_dto.WorkOrderDispenserRequest"
                    }
                },
                "locality": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3
                },
                "nroCta": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "nroRto": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "tipoAccion": {
                    "type": "string",
                    "enum": [
                        "Instalacion",
                        "Retiro",
                        "Recambio"
                    ]
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_models.CustomDate": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_models.Delivery": {
            "type": "object",
            "required": [
                "cantidad",
                "entregado_por",
                "estado",
                "nro_cta",
                "nro_rto",
                "tipo_entrega"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "cantidad": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 1
                },
                "created_at": {
                    "type": "string"
                },
                "dispensers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GoFrioCalor_internal_models.Dispenser"
                    }
                },
                "entregado_por": {
                    "enum": [
                        "Repartidor",
                        "Tecnico"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.EntregadoPor"
                        }
                    ]
                },
                "estado": {
                    "enum": [
                        "Pendiente",
                        "Completado",
                        "Cancelado"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.EstadoEntrega"
                        }
                    ]
                },
                "fecha_accion": {
                    "$ref": "#/definitions/GoFrioCalor_internal_models.CustomDate"
                },
                "id": {
                    "type": "integer"
                },
                "locality": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nro_cta": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "nro_rto": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "session_id": {
                    "type": "string"
                },
                "terms_session_id": {
                    "type": "integer"
                },
                "tipo_entrega": {
                    "enum": [
                        "Instalacion",
                        "Retiro",
                        "Recambio"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.TipoEntrega"
                        }
                    ]
                },
                "token": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_models.Dispenser": {
            "type": "object",
            "required": [
                "delivery_id",
                "marca",
                "nro_serie",
                "tipo"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delivery_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "marca": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "nro_serie": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "tipo": {
                    "enum": [
                        "A",
                        "B",
                        "C",
                        "HELADERA",
                        "P",
                        "M"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/GoFrioCalor_internal_models.TipoDispenser"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "GoFrioCalor_internal_models.EntregadoPor": {
            "type": "string",
            "enum": [
                "Repartidor",
                "Tecnico"
            ],
            "x-enum-varnames": [
                "Repartidor",
                "Tecnico"
            ]
        },
        "GoFrioCalor_internal_models.EstadoEntrega": {
            "type": "string",
            "enum": [
                "Pendiente",
                "Completado",
                "Cancelado"
            ],
            "x-enum-varnames": [
                "Pendiente",
                "Completado",
                "Cancelado"
            ]
        },
        "GoFrioCalor_internal_models.TipoDispenser": {
            "type": "string",
            "enum": [
                "A",
                "B",
                "C",
                "HELADERA",
                "P",
                "M"
            ],
            "x-enum-comments": {
                "TipoDispenserMesada": "Dispenser de mesada",
                "TipoDispenserPie": "Dispenser de pie"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "Dispenser de pie",
                "Dispenser de mesada"
            ],
            "x-enum-varnames": [
                "TipoDispenserA",
                "TipoDispenserB",
                "TipoDispenserC",
                "TipoDispenserHeladera",
                "TipoDispenserPie",
                "TipoDispenserMesada"
            ]
        },
        "GoFrioCalor_internal_models.TipoEntrega": {
            "type": "string",
            "enum": [
                "Instalacion",
                "Retiro",
                "Recambio"
            ],
            "x-enum-varnames": [
                "Instalacion",
                "Retiro",
                "Recambio"
            ]
        }
    },
    "tags": [
        {
            "description": "Operaciones relacionadas con entregas de dispensers",
            "name": "Deliveries"
        },
        {
            "description": "Flujo integrado de entregas con términos y condiciones",
            "name": "Deliveries with Terms"
        },
        {
            "description": "Endpoints para la aplicación móvil",
            "name": "Mobile"
        },
        {
            "description": "Gestión de dispensers",
            "name": "Dispensers"
        },
        {
            "description": "Generación de órdenes de trabajo en PDF",
            "name": "Work Orders"
        },
        {
            "description": "Gestión de sesiones de términos y condiciones",
            "name": "Terms"
        },
        {
            "description": "Health check del servicio",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8095",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "GoFrioCalor API",
	Description:      "API para gestión de entregas, dispensers y órdenes de trabajo de GoFrioCalor\nEsta API permite gestionar el ciclo completo de entregas, desde la creación hasta la finalización,\nincluyendo validación de términos y condiciones, integración con Infobip y flujos móviles.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
